### ISSUE TITLE
Can't find/use services which are already running on the network

### ISSUE THREAD

**Issue by Majonsi** [ursiform/sleuth#2]
Hi !
I have this code running on multiple computers on the same network

```go
package main


import (
	"bytes"
	"fmt"
	"github.com/gorilla/mux"
	"github.com/ursiform/sleuth"
	"net/http"
	"time"
)

var (
	client *sleuth.Client
)

func handler(res http.ResponseWriter, req *http.Request) {
	fmt.Println("test :D")
}

func main() {
	router := mux.NewRouter()
	router.HandleFunc("/", handler).Methods("POST")
	client, _ = sleuth.New(&sleuth.Config{Service: "comment-service", Handler: router})

	go surveilCurrentAvailableServices()

	fmt.Println("ready...")
	http.ListenAndServe(":9872", router)
}

func surveilCurrentAvailableServices() {
	for {
		fmt.Println(client)
		client.WaitFor("comment-service")

		//try to make a post to the another services
		input := "This is the value I am inputting."
		body := bytes.NewBuffer([]byte(input))
		request, _ := http.NewRequest("POST", "sleuth://comment-service/", body)
		client.Do(request)
		time.Sleep(500 * time.Millisecond)
	}
}
```

I run the code first on C1 (computer 1) then C2 and then C3

With the `fmt.Println(client)` I get this client object:
- On C1:
`&{500ms 0xc8201046e0 false SLEUTH-v1 145 0xc8200145a0 0xc820102470 0xc8200e2128 0xc820014640 map[B18125:comment-service F5C8BB:comment-service] 0xc820102480}`

- On C2 
`&{500ms 0x107ce3d0 false SLEUTH-v1 0 0x10712540 0x107cc120 0x107be7bc 0x10712630 map[B18125:comment-service] 0x107cc128}`

- On C3:
`&{500ms 0x107ce3d0 false SLEUTH-v1 0 0x10712540 0x107cc120 0x107be7cc 0x10712630 map[] 0x107cc128}`

So C1 detect C2 and C3 but C3 doesn't find the service of C1.
So when you run the code sleuth doesn't find services which are already running on another devices on the network. 

Is that an issue or is there a solution for that?

Moreover the POST request made on `sleuth://comment-service/` doesn't work and I doesn't understand why.

Thanks in advance!

Best regards

**Comment by afshin** [comment]
@Majonsi Hi! Thanks for the issue. I'll be taking a look at this later in the week, but in the interim: 
* Could you double-check that all of your machines allow UDP traffic on port `5670`?
* Could you increase your `client.Timeout` value, maybe to 5 seconds just to see?

**Comment by Majonsi** [comment]
Hi! Thanks for your quick answer!
Before all I have to say that I'm currently working on Linux and I installed the version 4.2 of zero mq.

I checked and my machines allow UDP traffic on the port 5670. 
I made some research and I found that the code is listening 2 ports:
- 9872: it normal its the server of the application 
- 62640 : this value change each time I run the code. I suppose that zero Mq is not listening the port 5670 but a random value.

**Comment by afshin** [comment]
@Majonsi I can confirm some version of this behavior is happening for me as well. I've been trying to track it down, but I don't yet have the solution. Will keep you posted here!

**Comment by Majonsi** [comment]
Hi ! I made a try with the 4.1.5 version (same as the version in your installation script) of zmq and this time the code is listening the right port (5670) but there is always the problem to find services which are already running on the network. 
Good luck !

I will posted here too!

**Comment by afshin** [comment]
@Majonsi okay! So I wasn't thinking about this clearly at all before and missed the forest for the trees. Basically, the order things are happening matters: your web server blocks and so does the sleuth client waiting for services. So in normal circumstances, you'd never run into this because a service is rarely going to wait for another service with the same exact name as itself, but in this case since all of the services suffer from the same design, at least one gets stuck. I refactored your code and put a lot of comments in explaining what I did. Let me know if it works for you. Also, be sure to set the `Interface` value of the configuration options! On Linux, you can run the `ifconfig` command to see the list of available interfaces and pick the right one.

```go
package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"time"

	"github.com/gorilla/mux"
	"github.com/ursiform/sleuth"
)

const name = "comment-service"

var client *sleuth.Client

// Handle web requests.
func handler(res http.ResponseWriter, req *http.Request) {
	fmt.Println("server received request :D")
}

// Run the web server.
func serve(fatal chan error, router *mux.Router) {
	// Pass the address/port of the server in via command line.
	var addr string

	flag.StringVar(&addr, "addr", "", "enter an addr such as :9872")
	flag.Parse()
	if addr == "" {
		fmt.Println("enter an addr for the web server to use")
		os.Exit(0)
	}

	router.HandleFunc("/", handler).Methods("POST")
	fmt.Println("server ready...")
	fatal <- http.ListenAndServe(addr, router)
}

// Surveil the network and make requests to available services.
func surveil() {
	for {
		client.WaitFor(name)

		// Communicate with a service on the network.
		input := "This is the value I am inputting."
		body := bytes.NewBuffer([]byte(input))
		url := fmt.Sprintf("sleuth://%s/", name)
		request, _ := http.NewRequest("POST", url, body)

		client.Do(request)
		time.Sleep(500 * time.Millisecond)
	}
}

func main() {
	// Create an HTTP router.
	router := mux.NewRouter()

	// Unless you are running these processes on the same machine, you should
	// pass in the `Interface` option so that you know all your services are on
	// the same subnet.
	client, _ = sleuth.New(&sleuth.Config{Service: name, Handler: router})

	// Surveil the system.
	go surveil()

	// Start the service in a separate goroutine so that surveillance of the
	// distributed system is possible. Create an error channel that waits for the
	// server to fail or just keeps running until the program has quit.
	fatality := make(chan error)
	go serve(fatality, router)
	log.Fatal(<-fatality)
}

**Comment by afshin** [comment]
In fact, the `main` function could just as easily be:

```go
func main() {
  // Create an HTTP router.
  router := mux.NewRouter()

  // Unless you are running these processes on the same machine, you should
  // pass in the `Interface` option so that you know all your services are on
  // the same subnet.
  client, _ = sleuth.New(&sleuth.Config{Service: name, Handler: router})

  // Surveil the system.
  go surveil()

  // Pass the address/port of the server in via command line.
  var addr string

  flag.StringVar(&addr, "addr", "", "enter an addr such as :9872")
  flag.Parse()
  if addr == "" {
    fmt.Println("enter an addr for the web server to use")
    os.Exit(0)
  }

  router.HandleFunc("/", handler).Methods("POST")
  fmt.Println("server ready...")

  // Start the service.
  log.Fatal(http.ListenAndServe(addr, router))
}
```

Or if you like the separation into functions, it could be

```go
func main() {
	// Create an HTTP router.
	router := mux.NewRouter()

	// Unless you are running these processes on the same machine, you should
	// pass in the `Interface` option so that you know all your services are on
	// the same subnet.
	client, _ = sleuth.New(&sleuth.Config{Service: name, Handler: router})

	// Surveil the system.
	go surveil()

	// Start the service. Create an error channel that waits for the server to
  // fail or just keeps running until the program has quit.
	fatality := make(chan error)
	serve(fatality, router)
	log.Fatal(<-fatality)
}
```

That is to say, it does not *have* to run in a separate goroutine.

**Comment by Majonsi** [comment]
Hi @afshin ,
Thanks for your complete answer. And it works! I tried your code and I changed the interface with this characteristics:

```
	client, _ = sleuth.New(&sleuth.Config{
		Service:   name,
		Handler:   router,
		Interface: "eth0",
		Port:      5781,
		LogLevel:  "debug"})
```

The set of the interface solve 2 problem (I think): 
- The post are made on the right interface (eth0)
- The port number is fix (On my old code the port number was a random value)
Now all the computers find the another one service with the same name, send and receive the messages! Sleuth is really magic!

Thank you again! And this issue is officially closed :D

**Comment by afshin** [comment]
Glad to hear it!

**Comment by mf-00** [comment]
Hi @afshin , my situation is that there are multiple nodes of similar type running in the same LAN and I want to communicate with them to get each's information. Seems in Sleuth, the nodes are required to be of different service names. Could Sleuth solve the problem, or is there some suggestion? Thanks.

**Comment by fengzie** [comment]
Hi @afshin ,

Does it work on wndows? I ran both server and client of the echo service sample on the same machine, both were blocked with no findings.

Server:

>  2018/06/24 13:32:04 <-[31;103m[**warning**]<-[0m sleuth: config.Interface not defined [801]
>  2018/06/24 13:32:05 <-[30;106m[ listening ]<-[0m sleuth: [SLEUTH-v1:5670][echo-service C37A1D]

Client:
>  2018/06/24 13:32:00 [initialized] sleuth: config.Handler is nil, client-only mode
>  2018/06/24 13:32:00 <-[31;103m[**warning**]<-[0m sleuth: config.Interface not defined [801]
>  2018/06/24 13:32:00 <-[30;106m[ listening ]<-[0m sleuth: [SLEUTH-v1:5670][client-only 4E170E]
>  2018/06/24 13:32:00 <-[1;38;5;255;48;5;165m[**blocked**]<-[0m sleuth: waiting forclient to find [echo-service]

**Comment by afshin** [comment]
@fengzie I've never used `sleuth` in Windows so I'm not sure what is happening, but if you have defined the `Interface` in your config and there isn't any firewall preventing your services from talking to each other, it should be fine. In particular, make sure your firewall allows UDP traffic on port 5670.

**Comment by fengzie** [comment]
Hi @afshin , thanks, maybe. however, both the client and server are running on the same pc, should the firewall be checked? Another question is that we don't know the active interface beforehand, it may have different name on different platform, should we find out it first?

**Comment by afshin** [comment]
You need to make sure both client and server are running on the same interface. Just to test, consider turning off your firewall and hard-coding the interface. If that works, then you can work backwards from there until you get to the configuration you want.

**Comment by fengzie** [comment]
Thank you @afshin for your kind reply.
