### ISSUE TITLE
Issue with UDP communication on finding a service

### ISSUE THREAD

**Issue by hasancana** [ursiform/sleuth#3]
I am having an issue with service discovery using Sleuth. I have followed your example without any changes except specifying the interface on the config. I've also made sure all UDP/TCP ports are open but still my client is not able to discover the service, it just keeps hanging on WaitFor(). If I run the service and client on same machine it works obviously but not when I run them on different machines on the same network. 

I have been using Sleuth with latest Gyre version (go get <gyre-repo>) and libzmq 4.2.1/4.2.3.

Is there any specific version of Gyre and libzmq that Sleuth requires as it seems Sleuth hasn't been updated for quite some time.

**Comment by afshin** [comment]
Thanks for the bug report! I'll investigate in the next few days and get back to you!

**Comment by afshin** [comment]
Hi @hasancana.

Right! Sorry for the delay, but I finally managed to get a test setup with two machines on the same network using the latest version of ZeroMQ. So my client config looks like:
```go
config := &sleuth.Config{Interface: "en0", LogLevel: "debug"}
```
And my server config looks like:
```go
config := &sleuth.Config{
  Handler:   handler,
  Interface: "en0",
  LogLevel:  "debug",
  Service:   "echo-service",
}
```
With this set up, the client and server in the example work. Have you defined `Interface` in both your client and your server? Here is what my client output including all the debug information looks like:

```
2018/03/21 10:18:47 [initialized] sleuth: config.Handler is nil, client-only mode
2018/03/21 10:18:47 [ listening ] sleuth: [SLEUTH-v1:5670][client-only 6218B6]
2018/03/21 10:18:47 [**blocked**] sleuth: waiting for client to find [echo-service]
2018/03/21 10:18:47 [information] sleuth: add echo-service/unknown 9C7780 to SLEUTH-v1
2018/03/21 10:18:47 [*unblocked*] sleuth: client found [echo-service]
2018/03/21 10:18:47 [   debug   ] sleuth: POST sleuth://echo-service/ via 9C7780
It works.
2018/03/21 10:18:47 [information] 6218B6 leaving SLEUTH-v1...
2018/03/21 10:18:47 [**warning**] sleuth: 6218B6 Node is not responding to STOP command [802]
```

If you have `Interface` defined in both the client and server, the next place to look is not just that your network has the ports open but that it allows UDP broadcast. Depending on your environment, this may be your problem.
